/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  learn: [
    {type: 'autogenerated', dirName: 'learn'}
  ],
  use: [
    {type: 'autogenerated', dirName: 'use'}
  ],
  develop: [
    {
      type: 'autogenerated',
      dirName: 'develop'
   },
   { type: 'link', href: '/colonynetwork', label: 'Colony Network' },
   {
      type: 'category',
      label: 'Libraries',
      collapsible: false,
      items: [
        { type: 'link', href: '/colonysdk', label: 'Colony SDK' },
        { type: 'link', href: '/colonyjs', label: 'ColonyJS' },
      ]
    }
  ],
};

module.exports = sidebars;
